#!/usr/bin/env bash

# Changes active workspace

function get_current_display {
  hyprctl monitors -j | jq ".[] | select(.focused) | .id"
}

function get_unavailable_workspaces {
  DISPLAY=$(get_current_display)
  hyprctl workspaces -j | jq "[.[] | select(.monitorID != $DISPLAY) | .id]"
}

function get_workspace {
  curr=$1
  dir=$2
  UNAVAIL=$(get_unavailable_workspaces)
  python -c "
avail = list(set(range(1, 11)) - set(${UNAVAIL}))
curr_idx = avail.index(${curr})
new_idx = max(0, min(curr_idx + ${dir}, len(avail)))
print(avail[new_idx])
"
}

direction=$1
current=$2
if test "$direction" = "down"
then
  target=$(get_workspace "${current}" 1)
  echo "jumping to $target"
  hyprctl dispatch workspace "${target}"
elif test "$direction" = "up"
then
  target=$(get_workspace "${current}" -1)
  echo "jumping to $target"
  hyprctl dispatch workspace "${target}"
fi
