#!/usr/bin/env bash

# Retrieves number of monitors

workspace() {
  hyprctl monitors -j | jq "[.[].id] | length"
}

workspace
socat -u "UNIX-CONNECT:${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" - | while read -r _; do
  workspace
done
