#!/usr/bin/env bash

# Retrieves Hyprland workspaces

spaces (){
  workspace_windows=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: [.windows, .monitorID]}) | from_entries')
  seq 1 10 | jq --argjson value "${workspace_windows}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($value[.][0]//0), display: ($value[.][1]//0)})'
}

spaces
socat -u "UNIX-CONNECT:${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" - | while read -r _; do
  spaces
done
