#!/usr/bin/env bash

# Retrieves active workspace

workspace() {
  hyprctl monitors -j | jq -Mc 'map(.activeWorkspace.id)'
}

workspace
socat -u "UNIX-CONNECT:${XDG_RUNTIME_DIR}/hypr/${HYPRLAND_INSTANCE_SIGNATURE}/.socket2.sock" - | while read -r _; do
  workspace
done
